package com.streamefy.component.base

enum class StreamEnum {
    MORE,SINGLE,UP_DPAD_KEY,DOWN_DPAD_KEY,LEFT_DPAD_KEY,RIGHT_DPAD_KEY,KEYCODE_MEDIA_FAST_FORWARD,KEYCODE_MEDIA_REWIND,KEYCODE_MEDIA_PLAY_PAUSE,
    INDECATOR_VIEW,LOGOUT_VIEW,BOTTOM_EVENT_VIEW,DRAWER_VIEW,PAGINATION,BACKGROUND_VIDEO,KEYCODE_DPAD_CENTER,REMOVE_LONG_PRESS,
    /// home controller
    PLAY_RESUME,TRAILER,HOME_CLOSE,LAST_EVENT,
    RESET_PIN

}