package com.streamefy.component.base

enum class StreamEnum {
    MORE,SINGLE,UP_DPAD_KEY,DOWN_DPAD_KEY,LEFT_DPAD_KEY,RIGHT_DPAD_KEY,
    INDECATOR_VIEW,LOGOUT_VIEW,BOTTOM_EVENT_VIEW,DRAWER_VIEW,PAGINATION
}